/* eslint-disable */
// AUTOGENERATED
export const mappings = {
  "gear": 59648,
  "save": 59649,
  "detach": 59650,
  "undo": 59651,
  "minus": 59652,
  "plus": 59653,
  "reload": 59654,
  "redo": 59655,
  "open": 59656,
  "close": 59657,
  "edit": 59658
}

export type IconName =
"gear" |
"save" |
"detach" |
"undo" |
"minus" |
"plus" |
"reload" |
"redo" |
"open" |
"close" |
"edit"
