/* eslint-disable */
// AUTOGENERATED
export const mappings = {
  "add": 61543,
  "close": 61453,
  "gear": 61459,
  "save": 61465,
  "reload": 61470,
  "open": 61587,
  "undo": 61666,
  "detach": 61772,
  "pin": 61581
}

export type IconName =
"add" |
"close" |
"gear" |
"save" |
"reload" |
"open" |
"undo" |
"detach" |
"pin"
