const path = require('path')
const fs = require('fs')

const data = require(path.join(__dirname, '../ext/icons/icomoon.project.json'))

const names = data.iconSets[0].selection.map(c => c.name)

const text =
  `
/* eslint-disable */
// AUTOGENERATED
export const mappings = {
  ${data.iconSets[0].selection.map(c => `"${c.name}": ${c.code}`).join(',\n  ')}
}

export type IconName =\n${names.map(n => `"${n}"`).join(' |\n')}
`.trim() + '\n'

fs.writeFileSync(path.join(__dirname, '../src/components/Icon/icons.ts'), text)
