name: 'Release'
on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1

      - name: 'NPM Install'
        run: npm install

      - name: 'Run tests'
        run: npm test

      - name: 'Compile'
        run: npm run compile:prod

      - name: 'web-ext build'
        id: web-ext-build
        uses: kewisch/action-web-ext@fe10addf5d5e5ba6b78ffde720dd488a27d10e8c
        with:
          cmd: build
          source: ext

      - name: 'web-ext lint'
        uses: kewisch/action-web-ext@v1
        with:
          cmd: lint
          source: ext
          channel: listed

      - name: 'web-ext sign'
        id: web-ext-sign
        uses: kewisch/action-web-ext@fe10addf5d5e5ba6b78ffde720dd488a27d10e8c
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: listed
          metaDataFile: amo_metadata.json
          license: BSD-3-Clause
          licenseFile: LICENSE
          apiKey: ${{ secrets.FIREFOX_API_KEY }}
          apiSecret: ${{ secrets.FIREFOX_API_SECRET }}

      - name: 'Create Release'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.web-ext-sign.outputs.target || steps.web-ext-build.outputs.target }}
